### PR TITLE
Added on-request event

### PR DESCRIPTION
**Pull request by Inrego**
Subscribing to this event, allows you to change parameters right before
the file is uploaded.

### CODE REVIEW

**Comment by winhowes** [comment]
Events bubble asynchronously, so you the upload would begin before the event fired. I'm happy to merge it, I just want to make sure there's a use case for this. Can you help me understand the use case?

**Comment by Inrego** [comment]
They do? Are you sure? I've been using it successfully to dynamically set headers.

**Comment by winhowes** [comment]
Hmm, you're right that this is synchronous. I'm going to add some of the documentation.. I think the name should be `pre-upload` as that's a bit more explicit

**Comment by Inrego** [comment]
I just gave it the same name as similar event on iron-ajax.

**Comment by winhowes** [comment]
Yeah, I just thought it might be a bit better for it to be explicit. `Request` makes sense on ajax. I now actually think `beforeUpload` makes more sense than `pre-upload` as it follows wider conventions.. will update

**Pull request merged**
